/*
 * Created on 17 Jul 2017 ( Time 15:08:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.go2.classes.business.service;

import java.util.List;

import com.go2.classes.models.Promo;


/**
 * Business Service Interface for entity Promo.
 */
public interface PromoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Promo findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Promo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Promo save(Promo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Promo update(Promo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Promo create(Promo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
