/*
 * Created on 26 Aug 2017 ( Time 13:07:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.go2.classes.business.service;

import java.util.List;

import com.go2.classes.models.SocialLinks;

/**
 * Business Service Interface for entity SocialLinks.
 */
public interface SocialLinksService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	SocialLinks findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<SocialLinks> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	SocialLinks save(SocialLinks entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	SocialLinks update(SocialLinks entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	SocialLinks create(SocialLinks entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
