/*
 * Created on 28 Aug 2017 ( Time 15:04:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.go2.classes.models.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "slider"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="slider", catalog="go2classes" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SliderEntity.countAll", query="SELECT COUNT(x) FROM SliderEntity x" )
} )
public class SliderEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time")
    private Date       createdTime  ;

    @Column(name="slider_image_five", length=300)
    private String     sliderImageFive ;

    @Column(name="slider_image_four", length=300)
    private String     sliderImageFour ;

    @Column(name="slider_image_one", length=300)
    private String     sliderImageOne ;

    @Column(name="slider_image_three", length=300)
    private String     sliderImageThree ;

    @Column(name="slider_image_two", length=300)
    private String     sliderImageTwo ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SliderEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : created_time ( DATETIME ) 
    public void setCreatedTime( Date createdTime ) {
        this.createdTime = createdTime;
    }
    public Date getCreatedTime() {
        return this.createdTime;
    }

    //--- DATABASE MAPPING : slider_image_five ( VARCHAR ) 
    public void setSliderImageFive( String sliderImageFive ) {
        this.sliderImageFive = sliderImageFive;
    }
    public String getSliderImageFive() {
        return this.sliderImageFive;
    }

    //--- DATABASE MAPPING : slider_image_four ( VARCHAR ) 
    public void setSliderImageFour( String sliderImageFour ) {
        this.sliderImageFour = sliderImageFour;
    }
    public String getSliderImageFour() {
        return this.sliderImageFour;
    }

    //--- DATABASE MAPPING : slider_image_one ( VARCHAR ) 
    public void setSliderImageOne( String sliderImageOne ) {
        this.sliderImageOne = sliderImageOne;
    }
    public String getSliderImageOne() {
        return this.sliderImageOne;
    }

    //--- DATABASE MAPPING : slider_image_three ( VARCHAR ) 
    public void setSliderImageThree( String sliderImageThree ) {
        this.sliderImageThree = sliderImageThree;
    }
    public String getSliderImageThree() {
        return this.sliderImageThree;
    }

    //--- DATABASE MAPPING : slider_image_two ( VARCHAR ) 
    public void setSliderImageTwo( String sliderImageTwo ) {
        this.sliderImageTwo = sliderImageTwo;
    }
    public String getSliderImageTwo() {
        return this.sliderImageTwo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(createdTime);
        sb.append("|");
        sb.append(sliderImageFive);
        sb.append("|");
        sb.append(sliderImageFour);
        sb.append("|");
        sb.append(sliderImageOne);
        sb.append("|");
        sb.append(sliderImageThree);
        sb.append("|");
        sb.append(sliderImageTwo);
        return sb.toString(); 
    } 

}
