/*
 * Created on 28 Aug 2017 ( Time 15:04:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.go2.classes.models.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "slider"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="slider", catalog="go2classes" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="SliderEntity.countAll", query="SELECT COUNT(x) FROM SliderEntity x" )
} )
public class SliderEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_time")
    private Date       createdTime  ;

    @Column(name="image_url", length=600)
    private String     imageUrl ;

    @Column(name="title", length=300)
    private String     title ;

    @Column(name="description", columnDefinition="TEXT")
    private String     description ;

    @Column(name="url_title", length=300)
    private String     urlTitle ;

    @Column(name="url", length=600)
    private String     url ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SliderEntity() {
		super();
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getCreatedTime() {
		return createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	
	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrlTitle() {
		return urlTitle;
	}

	public void setUrlTitle(String urlTitle) {
		this.urlTitle = urlTitle;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public String toString() {
		return "SliderEntity [id=" + id + ", createdTime=" + createdTime + ", imageUrl=" + imageUrl + ", title=" + title
				+ ", description=" + description + ", urlTitle=" + urlTitle + ", url=" + url + "]";
	}


}
