/*
 * Created on 17 Jul 2017 ( Time 15:08:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.go2.classes.rest.controller;

import java.util.Date;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.go2.classes.business.service.PromoService;
import com.go2.classes.models.Promo;


/**
 * Spring MVC controller for 'Promo' management.
 */
@Controller
public class PromoRestController {

	@Resource
	private PromoService promoService;

	@RequestMapping(value = "/promo", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Promo> findAll() {
		return promoService.findAll();
	}

	@RequestMapping(value = "/promo/{id}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Promo findOne(@PathVariable("id") Long id) {
		return promoService.findById(id);
	}

	@RequestMapping(value = "/promo", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Promo create(@RequestBody Promo promo) {
		promo.setCreatedTime(new Date());
		return promoService.create(promo);
	}

	@RequestMapping(value = "/promo/{id}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Promo update(@PathVariable("id") Long id, @RequestBody Promo promo) {
		return promoService.update(promo);
	}

	@RequestMapping(value = "/promo/{id}", method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		promoService.delete(id);
	}

}
