/*
 * Created on 28 Aug 2017 ( Time 15:06:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.go2.classes.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import com.go2.classes.business.service.SliderService;
import com.go2.classes.business.service.mapping.SliderServiceMapper;
import com.go2.classes.data.repository.jpa.SliderJpaRepository;
import com.go2.classes.models.Slider;
import com.go2.classes.models.jpa.SliderEntity;

/**
 * Implementation of SliderService
 */
@Component
@Transactional
public class SliderServiceImpl implements SliderService {

	@Resource
	private SliderJpaRepository sliderJpaRepository;

	@Resource
	private SliderServiceMapper sliderServiceMapper;
	
	@Override
	public Slider findById(Long id) {
		SliderEntity sliderEntity = sliderJpaRepository.findOne(id);
		return sliderServiceMapper.mapSliderEntityToSlider(sliderEntity);
	}

	@Override
	public List<Slider> findAll() {
		Iterable<SliderEntity> entities = sliderJpaRepository.findAll();
		List<Slider> beans = new ArrayList<Slider>();
		for(SliderEntity sliderEntity : entities) {
			beans.add(sliderServiceMapper.mapSliderEntityToSlider(sliderEntity));
		}
		return beans;
	}

	@Override
	public Slider save(Slider slider) {
		return update(slider) ;
	}

	@Override
	public Slider create(Slider slider) {
		SliderEntity sliderEntity = new SliderEntity();
		sliderServiceMapper.mapSliderToSliderEntity(slider, sliderEntity);
		SliderEntity sliderEntitySaved = sliderJpaRepository.save(sliderEntity);
		return sliderServiceMapper.mapSliderEntityToSlider(sliderEntitySaved);
	}

	@Override
	public Slider update(Slider slider) {
		SliderEntity sliderEntity = sliderJpaRepository.findOne(slider.getId());
		sliderServiceMapper.mapSliderToSliderEntity(slider, sliderEntity);
		SliderEntity sliderEntitySaved = sliderJpaRepository.save(sliderEntity);
		return sliderServiceMapper.mapSliderEntityToSlider(sliderEntitySaved);
	}

	@Override
	public void delete(Long id) {
		sliderJpaRepository.delete(id);
	}

	public SliderJpaRepository getSliderJpaRepository() {
		return sliderJpaRepository;
	}

	public void setSliderJpaRepository(SliderJpaRepository sliderJpaRepository) {
		this.sliderJpaRepository = sliderJpaRepository;
	}

	public SliderServiceMapper getSliderServiceMapper() {
		return sliderServiceMapper;
	}

	public void setSliderServiceMapper(SliderServiceMapper sliderServiceMapper) {
		this.sliderServiceMapper = sliderServiceMapper;
	}

}
