/*
 * Java bean class for entity table slider 
 * Created on 28 Aug 2017 ( Date ISO 2017-08-28 - Time 15:08:29 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.go2.classes.models;

import java.io.Serializable;

import java.util.Date;

/**
 * Entity bean for table "slider"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Slider implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Long       id           ; // Primary Key

    private Date       createdTime  ;
    private String     sliderImageFive ;
    private String     sliderImageFour ;
    private String     sliderImageOne ;
    private String     sliderImageThree ;
    private String     sliderImageTwo ;

    /**
     * Default constructor
     */
    public Slider()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "BIGINT", NotNull : true ) 
     * @param id
     */
	public void setId( Long id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "BIGINT", NotNull : true ) 
     * @return the field value
     */
	public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : created_time ( DATETIME ) 
    /**
     * Set the "createdTime" field value
     * This field is mapped on the database column "created_time" ( type "DATETIME", NotNull : false ) 
     * @param createdTime
     */
    public void setCreatedTime( Date createdTime )
    {
        this.createdTime = createdTime;
    }
    /**
     * Get the "createdTime" field value
     * This field is mapped on the database column "created_time" ( type "DATETIME", NotNull : false ) 
     * @return the field value
     */
    public Date getCreatedTime()
    {
        return this.createdTime;
    }

    //--- DATABASE MAPPING : slider_image_five ( VARCHAR ) 
    /**
     * Set the "sliderImageFive" field value
     * This field is mapped on the database column "slider_image_five" ( type "VARCHAR", NotNull : false ) 
     * @param sliderImageFive
     */
    public void setSliderImageFive( String sliderImageFive )
    {
        this.sliderImageFive = sliderImageFive;
    }
    /**
     * Get the "sliderImageFive" field value
     * This field is mapped on the database column "slider_image_five" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getSliderImageFive()
    {
        return this.sliderImageFive;
    }

    //--- DATABASE MAPPING : slider_image_four ( VARCHAR ) 
    /**
     * Set the "sliderImageFour" field value
     * This field is mapped on the database column "slider_image_four" ( type "VARCHAR", NotNull : false ) 
     * @param sliderImageFour
     */
    public void setSliderImageFour( String sliderImageFour )
    {
        this.sliderImageFour = sliderImageFour;
    }
    /**
     * Get the "sliderImageFour" field value
     * This field is mapped on the database column "slider_image_four" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getSliderImageFour()
    {
        return this.sliderImageFour;
    }

    //--- DATABASE MAPPING : slider_image_one ( VARCHAR ) 
    /**
     * Set the "sliderImageOne" field value
     * This field is mapped on the database column "slider_image_one" ( type "VARCHAR", NotNull : false ) 
     * @param sliderImageOne
     */
    public void setSliderImageOne( String sliderImageOne )
    {
        this.sliderImageOne = sliderImageOne;
    }
    /**
     * Get the "sliderImageOne" field value
     * This field is mapped on the database column "slider_image_one" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getSliderImageOne()
    {
        return this.sliderImageOne;
    }

    //--- DATABASE MAPPING : slider_image_three ( VARCHAR ) 
    /**
     * Set the "sliderImageThree" field value
     * This field is mapped on the database column "slider_image_three" ( type "VARCHAR", NotNull : false ) 
     * @param sliderImageThree
     */
    public void setSliderImageThree( String sliderImageThree )
    {
        this.sliderImageThree = sliderImageThree;
    }
    /**
     * Get the "sliderImageThree" field value
     * This field is mapped on the database column "slider_image_three" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getSliderImageThree()
    {
        return this.sliderImageThree;
    }

    //--- DATABASE MAPPING : slider_image_two ( VARCHAR ) 
    /**
     * Set the "sliderImageTwo" field value
     * This field is mapped on the database column "slider_image_two" ( type "VARCHAR", NotNull : false ) 
     * @param sliderImageTwo
     */
    public void setSliderImageTwo( String sliderImageTwo )
    {
        this.sliderImageTwo = sliderImageTwo;
    }
    /**
     * Get the "sliderImageTwo" field value
     * This field is mapped on the database column "slider_image_two" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getSliderImageTwo()
    {
        return this.sliderImageTwo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(createdTime);
        sb.append("|");
        sb.append(sliderImageFive);
        sb.append("|");
        sb.append(sliderImageFour);
        sb.append("|");
        sb.append(sliderImageOne);
        sb.append("|");
        sb.append(sliderImageThree);
        sb.append("|");
        sb.append(sliderImageTwo);
        return sb.toString(); 
    } 


}
