/*
 * Created on 28 Aug 2017 ( Time 15:06:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.go2.classes.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.go2.classes.models.Slider;
import com.go2.classes.models.jpa.SliderEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SliderServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SliderServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SliderEntity' to 'Slider'
	 * @param sliderEntity
	 */
	public Slider mapSliderEntityToSlider(SliderEntity sliderEntity) {
		if(sliderEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Slider slider = map(sliderEntity, Slider.class);

		return slider;
	}
	
	/**
	 * Mapping from 'Slider' to 'SliderEntity'
	 * @param slider
	 * @param sliderEntity
	 */
	public void mapSliderToSliderEntity(Slider slider, SliderEntity sliderEntity) {
		if(slider == null) {
			return;
		}

		//--- Generic mapping 
		map(slider, sliderEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}