/*
 * Created on 26 Aug 2017 ( Time 13:07:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.go2.classes.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.go2.classes.models.SocialLinks;
import com.go2.classes.models.jpa.SocialLinksEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SocialLinksServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SocialLinksServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SocialLinksEntity' to 'SocialLinks'
	 * @param socialLinksEntity
	 */
	public SocialLinks mapSocialLinksEntityToSocialLinks(SocialLinksEntity socialLinksEntity) {
		if(socialLinksEntity == null) {
			return null;
		}

		//--- Generic mapping 
		SocialLinks socialLinks = map(socialLinksEntity, SocialLinks.class);

		return socialLinks;
	}
	
	/**
	 * Mapping from 'SocialLinks' to 'SocialLinksEntity'
	 * @param socialLinks
	 * @param socialLinksEntity
	 */
	public void mapSocialLinksToSocialLinksEntity(SocialLinks socialLinks, SocialLinksEntity socialLinksEntity) {
		if(socialLinks == null) {
			return;
		}

		//--- Generic mapping 
		map(socialLinks, socialLinksEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}